Expose config models
Aiven-Open/rohmu pull request #146
Opened 2023-10-04 16:39 UTC by joelynch

Expose the Rohmu config models and add a method `get_transfer_from_model` to get a `transfer` from the pydantic model rather than having to serialize as dict first.  This will help with typing and hopefully eventually reduce the number of copies of these pydantic models currently in our codebase.

Other small improvements:
* Pylance / VSCode doesn't like importing the re-exports in `rohmu/__init__.py`, I think the addition of this `__all__` will change this.
* field `notifier` was confusing on a pydantic model since it is not itself a pydantic class.  Better off just passing this in directly to `BaseTransfer.from_model`
* Since `StorageModelT` is not covariant, it is _not_ the case that, for instance, `S3Transfer < BaseStorage[StorageModel]`.  Mypy correctly claims we cannot make this TypeVar covariant because, for example, if `transfer: S3Transfer` and `model: StorageModel` then we can't call `transfer.from_model(model)`.  Instead I have just typed using `Any` which will reduce the amount of `type: ignore`s downstream.  Using the new `get_transfer_from_model` has more narrow generic typing and should probably be used more downstream where possible.

2023-10-05 08:48 UTC, giacomo-alzetta-aiven requested changes
I think this makes sense. But you missed a couple of places if we want to keep typing for 3.8.

2023-10-05 08:48 UTC, giacomo-alzetta-aiven commented on rohmu/factory.py
> +    raise InvalidConfigurationError(f"unsupported storage type {repr(storage_driver)}")
nit: could change `{repr(<expr>)}` with `{<expr>!r}`

2023-10-05 08:48 UTC, giacomo-alzetta-aiven commented on rohmu/transfer_pool.py
> +    def from_model(cls, model: StorageModel, notifier: Notifier | None = None) -> Self:
Shouldn't we use `Optional` here?

2023-10-05 13:38 UTC, joelynch commented on rohmu/transfer_pool.py
> +    def from_model(cls, model: StorageModel, notifier: Notifier | None = None) -> Self:
oops thanks

2023-10-06 03:36 UTC, fingon reviewed
Doesn't that notifier change break existing usage? 

(I know it is broken, and I think we use it in only place but in general we try to avoid breaking backwards compatibility.)

I don't have better suggestions for it though. Perhaps we just have to upgrade the dependency at same time as rohmu.

2023-10-06 07:45 UTC, giacomo-alzetta-aiven commented
> Doesn't that notifier change break existing usage?

Yeah that's true. I guess we should probably bump rohmu version at least and make sure that change can be easily adapted to in our own code.

2023-10-06 08:15 UTC, joelynch commented
> Doesn't that notifier change break existing usage?

True if anyone was using `BaseTransfer.from_model` or `StorageModel.notifier`.  I don't think those methods were (until this PR) really supposed to be part of the "public api" for this library ie the stuff in `rohmu/__init__.py`.

I am not super attached to the `notifier` change but I think it is worthwhile, happy to revert if we want.

2023-10-06 08:42 UTC, fingon commented
> True if anyone was using `BaseTransfer.from_model` or `StorageModel.notifier`. I don't think those methods were (until this PR) really supposed to be part of the "public api" for this library ie the stuff in `rohmu/__init__.py`.

I'm pretty sure we at least have internal use (in btar) of that notifier.

> I am not super attached to the `notifier` change but I think it is worthwhile, happy to revert if we want.

I think the change makes sense, it is mostly question of how to roll it in. Perhaps we can just merge this in and then fix the dependencies as they crop up.

2023-10-06 08:43 UTC, fingon approved these changes

2023-10-06 08:44 UTC, merged